//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstimateCreator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimateHeader
    {
        public int EST_ID { get; set; }
        public string EST_NO { get; set; }
        public Nullable<System.DateTime> EST_Date { get; set; }
        public string Campaign { get; set; }
    }
}
