//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstimateCreator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstimatePublication
    {
        public int EST_PUBID { get; set; }
        public string EST_Publication { get; set; }
        public Nullable<int> EST_ID { get; set; }
        public string Pub_Language { get; set; }
    }
}
