//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstimateCreator.Models
{
    using System;
    using System.Collections.Generic;
    using DataAccessLayer;
    using InterfaceLayer;
    
    
    public partial class UserDetail :IUserDetails
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }

        //public void Validate()
        //{

        //    ValidateLogin vdal = new ValidateLogin();
        //    vdal.Validate(this);
            


        //}
    }
}
